---
services:
  gotify:
    image: gotify/server
    container_name: gotify
    restart: unless-stopped
    networks:
      - proxy
    environment:
      - TZ=${TZ}
    volumes:
      - gotify-data:/app/data

networks:
  proxy:
    external: true

volumes:
  gotify-data:
